name: Windows

on:
  release:
    types:
      - published

jobs:

  build:

    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore EmpathicQubit.ConsoleServer.sln
 
    - name: Build 
      run: msbuild EmpathicQubit.ConsoleServer.sln /p:Configuration=Release

    - uses: bruceadams/get-release@v1.2.2
      id: get_release
      name: Get Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: EmpathicQubit.ConsoleServer/bin/DragonbornSpeaksNaturallyApi.Release.zip
        asset_name: DragonbornSpeaksNaturallyApi.${{ steps.get_release.outputs.tag_name }}.zip
        asset_content_type: application/zip
